-- Run this in your Supabase SQL editor

-- Clients table: links a Supabase auth user to their Google Sheet
create table public.clients (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  spreadsheet_id text not null default '',  -- Google Sheets ID for this client (empty for coach)
  sex text not null default 'Male' check (sex in ('Male', 'Female')),
  is_coach boolean not null default false,
  package_end_date date,                    -- Optional: when their package ends (for retention alerts)
  whatsapp_number text,                     -- Optional: client WhatsApp number for nudges (e.g. +61412345678)
  drive_folder_url text,                    -- Google Drive folder URL for this client
  trainerize_url text,                      -- Trainerize profile link
  legal_docs_url text,                      -- Signed legal docs (Google Drive)
  onboarding_form_url text,                 -- Their onboarding form link
  -- Onboarding checklist
  step_form_sent boolean not null default false,
  step_terms_signed boolean not null default false,
  step_trainerize_setup boolean not null default false,
  step_tracker_created boolean not null default false,
  step_bloods_reminder_sent boolean not null default false,
  step_intro_call_done boolean not null default false,
  created_at timestamptz default now()
);

-- Migration: if adding to an existing table, run:
-- alter table public.clients add column if not exists is_coach boolean not null default false;
-- alter table public.clients alter column spreadsheet_id set default '';
-- alter table public.clients add column if not exists package_end_date date;
-- alter table public.clients add column if not exists whatsapp_number text;
-- alter table public.clients add column if not exists drive_folder_url text;
-- alter table public.clients add column if not exists trainerize_url text;
-- alter table public.clients add column if not exists legal_docs_url text;
-- alter table public.clients add column if not exists onboarding_form_url text;
-- alter table public.clients add column if not exists step_form_sent boolean not null default false;
-- alter table public.clients add column if not exists step_terms_signed boolean not null default false;
-- alter table public.clients add column if not exists step_trainerize_setup boolean not null default false;
-- alter table public.clients add column if not exists step_tracker_created boolean not null default false;
-- alter table public.clients add column if not exists step_bloods_reminder_sent boolean not null default false;
-- alter table public.clients add column if not exists step_intro_call_done boolean not null default false;

-- Only the user can read their own row; coach can read all via service role
alter table public.clients enable row level security;

create policy "Users can read own profile"
  on public.clients for select
  using (auth.uid() = id);

-- Coach admin view (used server-side with service role key — bypasses RLS)
-- No additional policy needed for service role

-- ============================================================
-- Blood Tests table (run in Supabase SQL editor)
-- ============================================================

create table public.blood_tests (
  id uuid default gen_random_uuid() primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  uploaded_at timestamptz default now() not null,
  file_path text not null,           -- Supabase Storage path: {client_id}/{timestamp}-{filename}
  file_name text not null,           -- Original filename shown in UI
  file_type text not null,           -- MIME type: application/pdf or image/*
  test_date date,                    -- Optional: date on the actual blood test
  ai_interpretation text,            -- Generated by Claude via /api/blood-tests/[id]/analyse
  coach_notes text,                  -- Coach's notes added before releasing
  status text not null default 'pending' check (status in ('pending', 'analysed', 'released')),
  released_at timestamptz            -- When coach released the interpretation to the client
);

alter table public.blood_tests enable row level security;

-- Clients can upload and view their own tests
create policy "Clients can insert own blood tests"
  on public.blood_tests for insert
  with check (auth.uid() = client_id);

create policy "Clients can view own blood tests"
  on public.blood_tests for select
  using (auth.uid() = client_id);

-- ============================================================
-- Xero OAuth tokens (single row, id = 1)
-- ============================================================

create table public.xero_tokens (
  id integer primary key,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  tenant_id text not null,
  updated_at timestamptz default now()
);

-- Only accessible server-side via service role key — lock down all client access
alter table public.xero_tokens enable row level security;

-- No RLS policies: service role bypasses RLS; anon/authenticated users get no access

-- ============================================================
-- Supabase Storage bucket (create in Supabase dashboard > Storage)
-- ============================================================
-- 1. Create a new bucket named: blood-tests
-- 2. Set to Private (not public)
-- 3. No additional storage policies needed — all access goes via service role key server-side
